openapi: 3.0.1
info:
  title: XYZApi
  description: API Definition of XYZApi
  version: 1.0.0
servers:
- url: http://localhost:8290/xyzapi
paths:
  /:
    get:
      responses:
        default:
          description: Default response
